package doricolib

import (
	"fmt"
	"log"
	"strings"
)

type Technique struct {
	Id   string
	Name string
}

var techniquesByName = make(map[string]Technique)

func init() {
	for _, technique := range Techniques {
		techniquesByName[technique.Name] = technique
	}
}

// Return a Technique for a given name
func GetTechniqueByName(name string) *Technique {
	if strings.HasPrefix(name, "Custom: ") {
		k := strings.Index(name, "\"")
		j := strings.LastIndex(name, "\"")
		n := name[k+1 : j]
		return &Technique{
			Id: fmt.Sprintf("pt.user.%s", n),
			Name: n,
		}
	}
	t, ok := techniquesByName[name]
	if !ok {
		log.Printf("no such technique: %s", name)
		panic("aborting")
	}
	return &t
}

var Techniques = []Technique{
	{Name: "Accent", Id: "pt.accent"},
	{Name: "Alternative fingering", Id: "pt.alternativeFingering"},
	{Name: "Arpeggio down", Id: "pt.arpeggioDown"},
	{Name: "Arpeggio up", Id: "pt.arpeggioUp"},
	{Name: "Artificial harmonic", Id: "pt.artificialHarmonic"},
	{Name: "Backstick", Id: "pt.backstick"},
	{Name: "Bartok/snap pizzicato", Id: "pt.bartoksnapPizzicato"},
	{Name: "Bass tone", Id: "pt.bassTone"},
	{Name: "Bell mute", Id: "pt.bellMute"},
	{Name: "Bell", Id: "pt.bell"},
	{Name: "Bend", Id: "pt.bend"},
	{Name: "Bow on bridge", Id: "pt.bowOnBridge"},
	{Name: "Bow on tailpiece", Id: "pt.bowOnTailpiece"},
	{Name: "Bowed", Id: "pt.bowed"},
	{Name: "Bowl hit", Id: "pt.hitBowl"},
	{Name: "Bucket mute", Id: "pt.bucketMute"},
	{Name: "Buzz pizzicato", Id: "pt.buzzPizzicato"},
	{Name: "Buzz roll", Id: "pt.buzzRoll"},
	{Name: "Cage hit", Id: "pt.hitCage"},
	{Name: "Centre", Id: "pt.centre"},
	{Name: "Choke", Id: "pt.choke"},
	{Name: "Chorus", Id: "pt.chorus"},
	{Name: "Circular roll", Id: "pt.circularRoll"},
	{Name: "Click", Id: "pt.click"},
	{Name: "Closed end", Id: "pt.closedEnd"},
	{Name: "Closed hole", Id: "pt.closedHole"},
	{Name: "Closed", Id: "pt.closed"},
	{Name: "Col legno battuto", Id: "pt.colLegnoBattuto"},
	{Name: "Col legno tratto", Id: "pt.colLegnoTratto"},
	{Name: "Collé", Id: "pt.colle"},
	{Name: "Con vibrato", Id: "pt.conVibrato"},
	{Name: "Crescendo", Id: "pt.crescendo"},
	{Name: "Crescendo-diminuendo", Id: "pt.crescendoDiminuendo"},
	{Name: "Cross stick", Id: "pt.crossStick"},
	{Name: "Crunch choke", Id: "pt.crunchChoke"},
	{Name: "Crunch", Id: "pt.crunch"},
	{Name: "Crush (dry)", Id: "pt.crushDry"},
	{Name: "Crush (fat)", Id: "pt.crushFat"},
	{Name: "Crush", Id: "pt.crush"},
	{Name: "Cuivré", Id: "pt.cuivre"},
	{Name: "Cup mute", Id: "pt.cupMute"},
	{Name: "Damp", Id: "pt.damp"},
	{Name: "Dead stroke", Id: "pt.deadStroke"},
	{Name: "Delay", Id: "pt.delay"},
	{Name: "Detaché lancé", Id: "pt.detacheLance"},
	{Name: "Diminuendo crescendo", Id: "pt.diminuendoCrescendo"},
	{Name: "Diminuendo", Id: "pt.diminuendo"},
	{Name: "Ding", Id: "pt.ding"},
	{Name: "Dip/bend", Id: "pt.dipbend"},
	{Name: "Distortion", Id: "pt.distortion"},
	{Name: "Doit", Id: "pt.doit"},
	{Name: "Double-tongue", Id: "pt.doubleTongue"},
	{Name: "Down", Id: "pt.down"},
	{Name: "Downbow", Id: "pt.downbow"},
	{Name: "Dreads (beater)", Id: "pt.beaterDreads"},
	{Name: "Dress harness hit", Id: "pt.harnessHit"},
	{Name: "Dut (vocal)", Id: "pt.vocalDut"},
	{Name: "Détaché", Id: "pt.detache"},
	{Name: "Edge (cymbals)", Id: "pt.edgeCymbals"},
	{Name: "Edge (drums)", Id: "pt.edgeDrums"},
	{Name: "Edge rebound", Id: "pt.edgeRebound"},
	{Name: "Fade in", Id: "pt.fadeIn"},
	{Name: "Fade out", Id: "pt.fadeOut"},
	{Name: "Fall (drop)", Id: "pt.fallDrop"},
	{Name: "Felt (beater)", Id: "pt.beaterFelt"},
	{Name: "Finger click", Id: "pt.fingerClick"},
	{Name: "Flange", Id: "pt.flange"},
	{Name: "Flat crash", Id: "pt.flatCrash"},
	{Name: "Flat roll", Id: "pt.flatRoll"},
	{Name: "Flautando", Id: "pt.flautando"},
	{Name: "Flip", Id: "pt.flip"},
	{Name: "Flutter-tongue", Id: "pt.flutterTongue"},
	{Name: "Fouetté", Id: "pt.fouette"},
	{Name: "Frame", Id: "pt.frame"},
	{Name: "Friction slide 1", Id: "pt.frictionSlide1"},
	{Name: "Friction slide 2", Id: "pt.frictionSlide2"},
	{Name: "Ga (open)", Id: "pt.tabla-ga"},
	{Name: "Ge (open)", Id: "pt.tabla-ge"},
	{Name: "Ghost note", Id: "pt.ghostNote"},
	{Name: "Gi (muted open)", Id: "pt.tabla-gi"},
	{Name: "Glissando down", Id: "pt.glissandoDown"},
	{Name: "Glissando up", Id: "pt.glissandoUp"},
	{Name: "Growl", Id: "pt.growl"},
	{Name: "Guitar pizzicato", Id: "pt.guitarPizzicato"},
	{Name: "Half harmonic", Id: "pt.halfHarmonic"},
	{Name: "Half muted", Id: "pt.halfMuted"},
	{Name: "Half open", Id: "pt.halfOpen"},
	{Name: "Harmon mute, stem extended", Id: "pt.harmonMuteStemExtended"},
	{Name: "Harmon mute, stem in", Id: "pt.harmonMuteStemIn"},
	{Name: "Harmon mute, stem out", Id: "pt.harmonMuteStemOut"},
	{Name: "Harp harmonic", Id: "pt.harpHarmonic"},
	{Name: "Hi-hat", Id: "pt.hiHat"},
	{Name: "Hit (loose)", Id: "pt.hitLoose"},
	{Name: "Hit (medium)", Id: "pt.hitMedium"},
	{Name: "Hit (tight)", Id: "pt.hitTight"},
	{Name: "Jazz turn", Id: "pt.jazzTurn"},
	{Name: "Jet whistle", Id: "pt.jetWhistle"},
	{Name: "Jeté", Id: "pt.jete"},
	{Name: "Ke (closed)", Id: "pt.tabla-ke"},
	{Name: "Key click with pitch", Id: "pt.keyClickWithPitch"},
	{Name: "Key click", Id: "pt.keyClick"},
	{Name: "LH pizzicato", Id: "pt.lhPizzicato"},
	{Name: "Laissez vibrer", Id: "pt.laissezVibrer"},
	{Name: "Left (LH)", Id: "pt.left"},
	{Name: "Left-hand tap", Id: "pt.leftHandTap"},
	{Name: "Legato", Id: "pt.legato"},
	{Name: "Loose", Id: "pt.loose"},
	{Name: "Marcato", Id: "pt.marcato"},
	{Name: "Martellato", Id: "pt.martellato"},
	{Name: "Martelé", Id: "pt.martele"},
	{Name: "Motor off", Id: "pt.motorOff"},
	{Name: "Motor on", Id: "pt.motorOn"},
	{Name: "Mouth closed", Id: "pt.mouthClosed"},
	{Name: "Mouth open", Id: "pt.mouthOpen"},
	{Name: "Mouth pursed", Id: "pt.mouthPursed"},
	{Name: "Mouth slightly open", Id: "pt.mouthSlightlyOpen"},
	{Name: "Mouth wide open", Id: "pt.mouthWideOpen"},
	{Name: "Mouthpiece pop", Id: "pt.mouthpiecePop"},
	{Name: "Muffled strings", Id: "pt.muffledStrings"},
	{Name: "Muffled/Damped", Id: "pt.muffledDamped"},
	{Name: "Multiphonic", Id: "pt.multiphonic"},
	{Name: "Muted", Id: "pt.muted"},
	{Name: "Na (open)", Id: "pt.tabla-na"},
	{Name: "Nail pizzicato", Id: "pt.nailPizzicato"},
	{Name: "Nail", Id: "pt.nail"},
	{Name: "Nasal voice", Id: "pt.nasalVoice"},
	{Name: "Natural harmonic 1", Id: "pt.naturalHarmonic1"},
	{Name: "Natural harmonic 2", Id: "pt.naturalHarmonic2"},
	{Name: "Natural", Id: "pt.natural"},
	{Name: "Non legato", Id: "pt.nonLegato"},
	{Name: "Non vibrato", Id: "pt.nonVibrato"},
	{Name: "Open 1", Id: "pt.open2"},
	{Name: "Open 2", Id: "pt.open1"},
	{Name: "Open end", Id: "pt.openEnd"},
	{Name: "Open hole", Id: "pt.openHole"},
	{Name: "Over the head double shot", Id: "pt.doubleShotOverTheHeader"},
	{Name: "Over the head hit", Id: "pt.hitOverTheHead"},
	{Name: "Over the head shot", Id: "pt.shotOverTheHead"},
	{Name: "Overdrive", Id: "pt.overdrive"},
	{Name: "Overpressure", Id: "pt.overpressure"},
	{Name: "P.d.l.t.", Id: "pt.pdlt"},
	{Name: "Palm muting", Id: "pt.palmMuting"},
	{Name: "Pedal", Id: "pt.pedal"},
	{Name: "Phaser", Id: "pt.phaser"},
	{Name: "Pick scrape", Id: "pt.pickScrape"},
	{Name: "Pinch harmonic", Id: "pt.pinchHarmonic"},
	{Name: "Pincé", Id: "pt.pince"},
	{Name: "Ping", Id: "pt.ping"},
	{Name: "Pizzicato alla chitarra", Id: "pt.pizzicatoAllaChitarra"},
	{Name: "Pizzicato secco", Id: "pt.pizzicatoSecco"},
	{Name: "Pizzicato", Id: "pt.pizzicato"},
	{Name: "Plop", Id: "pt.plop"},
	{Name: "Plucked", Id: "pt.plucked"},
	{Name: "Plunger mute", Id: "pt.plungerMute"},
	{Name: "Pop", Id: "pt.pop"},
	{Name: "Port crash", Id: "pt.portCrash"},
	{Name: "Portamento down", Id: "pt.portamentoDown"},
	{Name: "Portamento up", Id: "pt.portamentoUp"},
	{Name: "Portato/Louré", Id: "pt.portatoloure"},
	{Name: "Pre-bend", Id: "pt.preBend"},
	{Name: "Press roll", Id: "pt.pressRoll"},
	{Name: "Puffy (beater)", Id: "pt.beaterPuffy"},
	{Name: "Pull", Id: "pt.pull"},
	{Name: "Push", Id: "pt.push"},
	{Name: "Rake", Id: "pt.rake"},
	{Name: "Release", Id: "pt.release"},
	{Name: "Ricochet", Id: "pt.ricochet"},
	{Name: "Right (RH)", Id: "pt.right"},
	{Name: "Right hand tap", Id: "pt.rightHandTap"},
	{Name: "Right-hand tap (tapping)", Id: "pt.rightHandTapTapping"},
	{Name: "Rim knock", Id: "pt.rimKnock"},
	{Name: "Rim only", Id: "pt.rimOnly"},
	{Name: "Rim shot", Id: "pt.rimShot"},
	{Name: "Rim", Id: "pt.rim"},
	{Name: "Rip", Id: "pt.rip"},
	{Name: "Rods (beater)", Id: "pt.beaterRods"},
	{Name: "Roll", Id: "pt.roll"},
	{Name: "Saltando", Id: "pt.saltando"},
	{Name: "Sautillé", Id: "pt.sautille"},
	{Name: "Scoop", Id: "pt.scoop"},
	{Name: "Scrape (left)", Id: "pt.scrapeLeft"},
	{Name: "Scrape (right)", Id: "pt.scrapeRight"},
	{Name: "Scrape", Id: "pt.scrape"},
	{Name: "Scratch in", Id: "pt.scratchIn"},
	{Name: "Scratch out", Id: "pt.scratchOut"},
	{Name: "Shake", Id: "pt.shake"},
	{Name: "Shell", Id: "pt.shell"},
	{Name: "Side stick", Id: "pt.sideStick"},
	{Name: "Simile", Id: "pt.simile"},
	{Name: "Sizzle suck", Id: "pt.sizzleSuck"},
	{Name: "Sizzle", Id: "pt.sizzle"},
	{Name: "Skank", Id: "pt.skank"},
	{Name: "Skin", Id: "pt.skin"},
	{Name: "Slap (congas)", Id: "pt.slapCongas"},
	{Name: "Slap tongue", Id: "pt.slapTongue"},
	{Name: "Slap", Id: "pt.slap"},
	{Name: "Slide", Id: "pt.slide"},
	{Name: "Slight bend", Id: "pt.slightBend"},
	{Name: "Smear", Id: "pt.smear"},
	{Name: "Snares off", Id: "pt.snareOff"},
	{Name: "Snares on", Id: "pt.snareOn"},
	{Name: "Snenor", Id: "pt.snenor"},
	{Name: "Soft", Id: "pt.soft"},
	{Name: "Sons xylophoniques", Id: "pt.sonsXylophoniques"},
	{Name: "Sostenuto pedal", Id: "pt.sostenutoPedal"},
	{Name: "Spiccato", Id: "pt.spiccato"},
	{Name: "Spoken", Id: "pt.spoken"},
	{Name: "Squeeze", Id: "pt.squeeze"},
	{Name: "Staccatissimo", Id: "pt.staccatissimo"},
	{Name: "Staccato", Id: "pt.staccato"},
	{Name: "Stand click", Id: "pt.standClick"},
	{Name: "Stick (butt)", Id: "pt.stickButt"},
	{Name: "Stick (shaft)", Id: "pt.stickShaft"},
	{Name: "Stick (shoulder)", Id: "pt.stickShoulder"},
	{Name: "Stick (tip)", Id: "pt.stickTip"},
	{Name: "Stick click", Id: "pt.stickClick"},
	{Name: "Stick shot", Id: "pt.stickShot"},
	{Name: "Stick snap", Id: "pt.stickSnap"},
	{Name: "Sticks in", Id: "pt.sticksIn"},
	{Name: "Stir", Id: "pt.stir"},
	{Name: "Stopped", Id: "pt.stopped"},
	{Name: "Straight mute", Id: "pt.straightMute"},
	{Name: "Strum down", Id: "pt.strumDown"},
	{Name: "Strum up", Id: "pt.strumUp"},
	{Name: "Suck", Id: "pt.suck"},
	{Name: "Sul ponticello", Id: "pt.sulPonticello"},
	{Name: "Sul tasto", Id: "pt.sulTasto"},
	{Name: "Sustain pedal", Id: "pt.sustainPedal"},
	{Name: "Swish", Id: "pt.swish"},
	{Name: "Swoosh roll", Id: "pt.swooshRoll"},
	{Name: "Ta (muted open)", Id: "pt.tabla-ta"},
	{Name: "Tap at edge", Id: "pt.tapEdge"},
	{Name: "Tap choke", Id: "pt.tapChoke"},
	{Name: "Tap halfway", Id: "pt.tapHalfway"},
	{Name: "Tap", Id: "pt.tap"},
	{Name: "Te (closed)", Id: "pt.tabla-te"},
	{Name: "Tenuto", Id: "pt.tenuto"},
	{Name: "Throw", Id: "pt.throw"},
	{Name: "Throwoff off", Id: "pt.throwoffOff"},
	{Name: "Throwoff on", Id: "pt.throwoffOn"},
	{Name: "Ti (muted closed)", Id: "pt.tabla-ti"},
	{Name: "Tongue and finger click", Id: "pt.tongueFingerClick"},
	{Name: "Tongue click", Id: "pt.tongueClick"},
	{Name: "Tongue stop", Id: "pt.tongueStop"},
	{Name: "Tremblement", Id: "pt.tremblement"},
	{Name: "Tremolo", Id: "pt.tremolo"},
	{Name: "Trill (half-step)", Id: "pt.trill.half"},
	{Name: "Trill (whole step)", Id: "pt.trill.whole"},
	{Name: "Trill", Id: "pt.trill"},
	{Name: "Triple tongue", Id: "pt.tripleTongue"},
	{Name: "Tu (open)", Id: "pt.tabla-tu"},
	{Name: "Una corda", Id: "pt.unaCorda"},
	{Name: "Up", Id: "pt.up"},
	{Name: "Upbow", Id: "pt.upbow"},
	{Name: "Vacuum suck", Id: "pt.vacuumSuck"},
	{Name: "Vibrato bar dip", Id: "pt.vibratoBarDip"},
	{Name: "Vibrato bar line", Id: "pt.vibratoBarLine"},
	{Name: "Vibrato bar scoop", Id: "pt.vibratoBarScoop"},
	{Name: "Vibrato", Id: "pt.vibrato"},
	{Name: "Volume swell", Id: "pt.volumeSwell"},
	{Name: "Wah-wah open", Id: "pt.wahWahOpen"},
	{Name: "Wah-wah stopped", Id: "pt.wahWahStopped"},
	{Name: "Wah-wah", Id: "pt.wahWahGuitar"},
	{Name: "Whale call", Id: "pt.whaleCall"},
	{Name: "Whisper", Id: "pt.whisper"},
	{Name: "Whistle tone", Id: "pt.whistleTone"},
	{Name: "Whistle", Id: "pt.whistle"},
	{Name: "Wide vibrato", Id: "pt.wideVibrato"},
	{Name: "Zing (fast)", Id: "pt.zingFast"},
	{Name: "Zing (slow)", Id: "pt.zingSlow"},
	{Name: "Zing", Id: "pt.zing"},
	{Name: "f", Id: "pt.f"},
	{Name: "ff", Id: "pt.ff"},
	{Name: "fff", Id: "pt.fff"},
	{Name: "ffp", Id: "pt.ffp"},
	{Name: "fp", Id: "pt.fp"},
	{Name: "mf", Id: "pt.mf"},
	{Name: "mp", Id: "pt.mp"},
	{Name: "p", Id: "pt.p"},
	{Name: "pf", Id: "pt.pf"},
	{Name: "pp", Id: "pt.pp"},
	{Name: "ppp", Id: "pt.ppp"},
	{Name: "sf", Id: "pt.sf"},
	{Name: "sfp", Id: "pt.sfp"},
	{Name: "sfz", Id: "pt.sfz"},
}
